service: serverless

frameworkVersion: '2 || 3'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  architecture: arm64
  memorySize: 128
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: index.handler
    url: true
